### ISSUE TITLE
Embed the code into all the repos?

### ISSUE THREAD

**Issue by GildedHonour** [igrigorik/ga-beacon#24]
I have to embed the code into all README.md in all my repositories? Is there an easier way - embed it only in one repository? After, when it's forked, the code will track the person who's forked it.

**Comment by igrigorik** [comment]
Yes, you have to manually embed it into each file you want to track. If/when someone forks.. the same beacon will carry over to their fork. However, you won't see the  fork as a separate page, because the beacon is hardcoded and wouldn't reflect their username, etc. This is a limitation of not being able to run JS, there is no way around this.

P.s. Except, of course, GH does offer own analytics nowadays, so you might want to check that out.

**Comment by GildedHonour** [comment]
That's what I'm saying: after it's forked, it'll still track myself. And what if I want to track the main page of my github which is github.com/NNN? Impossible.
